// Comments

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';

// Auth

export const LOGIN_FORM_CHANGED = 'LOGIN_FORM_CHANGED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_NEXT = 'SIGNUP_NEXT';

// Links Receieved

export const LINKS_RECEIVED_REQUEST = 'LINKS_RECEIVED_REQUEST';
export const LINKS_RECEIVED_SUCCESS = 'LINKS_RECEIVED_SUCCESS';
export const LINKS_RECEIVED_FAILURE = 'LINKS_RECEIVED_FAILURE';

// Friends

export const FRIENDS_REQUEST = 'FRIENDS_REQUEST';
export const FRIENDS_SUCCESS = 'FRIENDS_SUCCESS';
export const FRIENDS_FAILURE = 'FRIENDS_FAILURE';

// Share / Friends Selection
export const SHARE_FRIEND_CELL_TAPPED = 'SHARE_FRIEND_CELL_TAPPED'
export const SHARE_FORM_CHANGED = 'SHARE_FORM_CHANGED'

export const SHARE_REQUEST = 'SHARE_REQUEST';
export const SHARE_SUCCESS = 'SHARE_SUCCESS';
export const SHARE_FAILURE = 'SHARE_FAILURE';
